development: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: easy_xml_db
  username: postgres
  password: postgres
  host: localhost
test: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: easy_xml_test_db
  username: postgres
  password: postgres
  host: localhost
